name: build & publish

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t youssefmobarak/app2-docker-java:latest
    - name: snyk container test
        uses: snyk/actions/docker@master
        continue-on-error: ${{ inputs.snykContinueOnError == 'true' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          image: youssefmobarak/app2-docker-java:latest
  Publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: Push image to dockerhub
      run: |
        docker login -u youssefmobarak -p ${{secrets.DOK_TOKEN}}
        docker push youssefmobarak/app2-docker-java:latest
      