name: Release Versioning

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release please action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout repository
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        uses: actions/checkout@v3
      - name: "Merge pull request"
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge -s ${{ fromJSON(steps.release.outputs.pr).number }} --admin